QT       += core gui
#network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000

CONFIG += c++20

DEFINES += TARGI=$$TARGET
message( "TARGET = "$$TARGI )
# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    calculation/lengthcalculator.cpp \
    cutting/export/cutinstructionservice.cpp \
    cutting/snapshot/cuttingsnapshotdeserializer.cpp \
    cutting/snapshot/cuttingsnapshotserializer.cpp \
    kitting/kittingengine.cpp \
    kitting/presenter/kittingpresenter.cpp \
    leftover/audit/leftoveraudit.cpp \
    leftover/view/dialog/leftoverauditdialog.cpp \
    model/cutting/optimizer/cutengine.cpp \
    model/cutting/optimizer/fitengine.cpp \
    model/cutting/optimizer/leftoverlifecycle.cpp \
    model/cutting/optimizer/reusablefitengine.cpp \
    model/cutting/optimizer/rodloopengine.cpp \
    model/cutting/optimizer/stockfitengine.cpp \
    model/cutting/plan/audit/audit_header_rules.cpp \
    model/cutting/plan/audit/audit_length_rules.cpp \
    model/cutting/plan/audit/product_bom_audit_service.cpp \
    model/storageaudit/auditcontext.cpp \
    paint/paint_calculator.cpp \
    paint/paint_reporter.cpp \
    paint/presenter/paintpresenter.cpp \
    paint/registry/powder_consumption_registry.cpp \
    paint/repository/powder_consumption_repository.cpp \
    leftover/presenter/leftoverpresenter.cpp \
    stock/presenter/stockpresenter.cpp \
    presenter/storageauditpresenter.cpp \
    product/registry/bom_registry.cpp \
    product/registry/material_role_registry.cpp \
    product/registry/product_subtype_registry.cpp \
    product/registry/product_type_registry.cpp \
    product/registry/productattributeregistry.cpp \
    product/repository/bom_repository.cpp \
    product/repository/material_role_repository.cpp \
    product/repository/product_subtype_repository.cpp \
    product/repository/product_type_repository.cpp \
    product/selector/material_selector.cpp \
    service/buildnumber.cpp \
    service/cutting/summary/cutplan_input_summary.cpp \
    service/cutting/summary/cutplan_input_summary_builder.cpp \
    service/cutting/summary/cutplan_output_summary.cpp \
    service/cutting/summary/cutplan_output_summary_builder.cpp \
    service/cutting/summary/cutplansummary.cpp \
    service/cutting/summary/cutplansummarybuilder.cpp \
    service/storageaudit/auditcontextbuilder.cpp \
    service/storageaudit/auditstatemanager.cpp \
    common/color/namedcolor.cpp \
    common/eventlogger.cpp \
    common/filehelper.cpp \
    common/filenamehelper.cpp \
    common/logger.cpp \
    common/quantityparser.cpp \
    settings/settingsdialog.cpp \
    settings/settingsmanager.cpp \
    common/startup/startupmanager.cpp \
    settings/settingsmeta.cpp \
    tests/testmanager.cpp \
    view/cellhelpers/auditstatustext.cpp \
    view/common/layouts/qflowlayout.cpp \
    view/common/widgets/recentmaterialswidget.cpp \
    view/dialog/input/clonerequestdialog.cpp \
    view/dialog/input/matrix_cell_delegate.cpp \
    view/dialog/input/series_matrix_view.cpp \
    view/dialog/materialfinder/materialdelegate.cpp \
    view/dialog/materialfinder/materialfinderdialog.cpp \
    view/dialog/materialsearch/materialsearchdialog.cpp \
    view/dialog/textviewdialog.cpp \
    leftover/view/dialog/leftoverreviewdialog.cpp \
    leftover/view/dialog/scrapbybarcodedialog.cpp \
    view/tableutils/auditgrouplabeler.cpp \
    view/tableutils/auditgroupsynchronizer.cpp \
    main.cpp \
    model/archivedwasteentry.cpp \
    model/crosssectionshape.cpp \
    model/cutting/cuttingmachine.cpp \
    model/cutting/optimizer/optimizermodel.cpp \
    model/cutting/piece/pieceinfo.cpp \
    model/cutting/piece/piecewithmaterial.cpp \
    model/cutting/plan/cutplan.cpp \
    model/cutting/plan/request.cpp \
    model/cutting/result/resultmodel.cpp \
    model/identifiableentity.cpp \
    leftover/model/leftoverstockentry.cpp \
    materials/model/material_type.cpp \
    model/picking/pickingcomparisonresult.cpp \
    model/picking/pickingitem.cpp \
    model/registries/cuttingmachineregistry.cpp \
    model/registries/cuttingplanrequestregistry.cpp \
    leftover/registry/leftoverstockregistry.cpp \
    materials/registry/material_group_registry.cpp \
    materials/registry/material_registry.cpp \
    stock/registry/stockregistry.cpp \
    storage/registry/storageregistry.cpp \
    model/relocation/relocationsourceentry.h \
    model/repositories/cuttingmachinerepository.cpp \
    model/repositories/cuttingrequestrepository.cpp \
    leftover/repository/leftoverstockrepository.cpp \
    materials/repository/material_group_repository.cpp \
    materials/repository/material_repository.cpp \
    stock/repository/stockrepository.cpp \
    storage/repository/storagerepository.cpp \
    stock/model/stockentry.cpp \
    storage/model/storagetype.cpp \
    presenter/CuttingPresenter.cpp \
    service/cutting/optimizer/exporter.cpp \
    service/cutting/plan/autosavemanager.cpp \
    service/cutting/result/archivedwasteutils.cpp \
    service/cutting/result/leftoversourceutils.cpp \
    service/cutting/segment/segmentutils.cpp \
    service/relocation/relocationplanner.cpp \
    service/relocation/relocationservice.cpp \
    leftover/audit/leftoverauditservice.cpp \
    service/storageaudit/storageauditservice.cpp \
    view/MainWindow.cpp \
    view/cutanalyticspanel.cpp \
    view/dialog/input/addinputdialog.cpp \
    leftover/view/dialog/addwastedialog.cpp \
    view/dialog/movement/movementdialog.cpp \
    view/dialog/relocation/relocationquantitydialog.cpp \
    stock/view/dialog/addstockdialog.cpp \
    stock/view/dialog/editcommentdialog.cpp \
    stock/view/dialog/editquantitydialog.cpp \
    stock/view/dialog/editstoragedialog.cpp \
    view/managers/cuttinginstructiontable_manager.cpp \
    view/managers/inputtable_manager.cpp \
    leftover/view/managers/leftovertable_manager.cpp \
    view/managers/relocationplantable_manager.cpp \
    view/managers/resultstable_manager.cpp \
    stock/view/stocktable_manager.cpp \
    view/managers/storageaudittable_manager.cpp \
    leftover/view/utils/leftoverreviewform_utils.cpp

HEADERS += \
    cutting/export/cutinstructionservice.h \
    cutting/export/sortmode.h \
    cutting/snapshot/CuttingSnapshotFormat.h \
    cutting/snapshot/cuttingsnapshotdeserializer.h \
    cutting/snapshot/cuttingsnapshotserializer.h \
    leftover/audit/leftoveraudit.h \
    leftover/view/dialog/leftoverauditdialog.h \
    product/utils/material_role_utils.h \
    product/utils/subtype_utils.h \
    stock/model/stockentry.h \
    calculation/calcmode.h \
    calculation/lengthcalculator.h \
    calculation/naphalo/calculation_naphalo_bowdenes.h \
    calculation/naphalo/calculation_naphalo_cipzaras.h \
    calculation/naphalo/calculation_naphalo_sines.h \
    calculation/naphalo/calculatuon_naphalo.h \
    common/barcodepainter.h \
    common/color/colorconstants.h \
    common/emojihelper.h \
    common/enum_utils.h \
    common/fontaudithelper.h \
    common/fontversionhelper.h \
    common/identifierutils.h \
    common/signalhelper.h \
    common/surface/surfacetype.h \
    common/sysinfohelper.h \
    common/testlabelmaker.h \
    common/texthelper.h \
    kitting/kittingengine.h \
    kitting/model/kittinginstruction.h \
    kitting/naphalo/kitting_naphalo.h \
    kitting/naphalo/kitting_naphalo_bowdenes.h \
    kitting/naphalo/kitting_naphalo_cipzaras.h \
    kitting/naphalo/kitting_naphalo_sines.h \
    kitting/presenter/kittingpresenter.h \
    materials/model/material_family.h \
    materials/model/material_family_utils.h \
    materials/model/scoringparams.h \
    materials/model/trimmingparams.h \
    model/cutting/optimizer/cutengine.h \
    model/cutting/optimizer/cuttypes.h \
    model/cutting/optimizer/discardedpiece.h \
    model/cutting/optimizer/fitengine.h \
    model/cutting/optimizer/inventoryhelper.h \
    model/cutting/optimizer/leftoverlifecycle.h \
    model/cutting/optimizer/lineagehelper.h \
    model/cutting/optimizer/machineselecthelper.h \
    model/cutting/optimizer/pendinganalyzer.h \
    model/cutting/optimizer/piecebuilder.h \
    model/cutting/optimizer/piecebuilder_toldas.h \
    model/cutting/optimizer/reusablefitengine.h \
    model/cutting/optimizer/rodloopengine.h \
    model/cutting/optimizer/segmentpostprocess.h \
    model/cutting/optimizer/selectedrod.h \
    model/cutting/optimizer/stockfitengine.h \
    model/cutting/optimizer/targetheuristic.h \
    model/cutting/optimizer/telemetryhelper.h \
    model/cutting/optimizer/toldas_engine.h \
    model/cutting/optimizer/toldasrole.h \
    model/cutting/plan/audit/audit_header_rules.h \
    model/cutting/plan/audit/audit_length_rules.h \
    model/cutting/plan/audit/naphalo_audit_types.h \
    model/cutting/plan/audit/naphalo_profile_postfix.h \
    model/cutting/plan/audit/product_bom_audit_service.h \
    model/cutting/plan/handlerside.h \
    model/cutting/plan/parentinfo.h \
    model/cutting/plan/relevantdimension.h \
    model/cutting/plan/segments.h \
    model/cutting/plan/tolerance.h \
    model/inventorysnapshot.h \
    leftover/leftoverstatus.h \
    leftover/leftoverstatusutils.h \
    leftover/leftoverutils.h \
    model/machine/machineutils.h \
    materials/model/cutting_mode.h \
    materials/utils/material_utils.h \
    materials/utils/material_group_utils.h \
    materials/model/painting_mode.h \
    model/relocation/relocationauditstatus.h \
    storage/utils/storageutils.h \
    model/storageaudit/audit_enums.h \
    paint/model/powder_consumption_model.h \
    paint/paint_calculator.h \
    paint/paint_plan.h \
    paint/paint_reporter.h \
    paint/presenter/paintpresenter.h \
    paint/registry/powder_consumption_registry.h \
    paint/repository/powder_consumption_repository.h \
    leftover/presenter/leftoverpresenter.h \
    stock/presenter/stockpresenter.h \
    presenter/storageauditpresenter.h \
    product/model/bom_entry.h \
    product/model/material_role.h \
    product/model/product_subtype.h \
    product/model/product_type.h \
    product/registry/bom_registry.h \
    product/registry/material_role_registry.h \
    product/registry/product_subtype_registry.h \
    product/registry/product_type_registry.h \
    product/registry/productattributeregistry.h \
    product/repository/bom_repository.h \
    product/repository/material_role_repository.h \
    product/repository/product_subtype_repository.h \
    product/repository/product_type_repository.h \
    product/selector/material_selector.h \
    service/buildnumber.h \
    service/cutting/instruction/cuttinginstructionutils.h \
    service/cutting/instruction/labelmodel.h \
    service/cutting/optimizer/optimizationauditbuilder.h \
    service/cutting/optimizer/optimizationlogger.h \
    service/cutting/optimizer/optimizationrunner.h \
    service/cutting/optimizer/optimizationviewupdater.h \
    service/cutting/optimizer/optimizerconstants.h \
    service/cutting/optimizer/optimizerutils.h \
    service/cutting/plan/requestutils.h \
    service/cutting/summary/cutplan_input_summary.h \
    service/cutting/summary/cutplan_input_summary_builder.h \
    service/cutting/summary/cutplan_output_summary.h \
    service/cutting/summary/cutplan_output_summary_builder.h \
    service/cutting/summary/cutplansummary.h \
    service/cutting/summary/cutplansummarybuilder.h \
    service/snapshot/inventorysnapshotbuilder.h \
    service/snapshot/requestsnapshotbuilder.h \
    service/storageaudit/auditcontextbuilder.h \
    service/storageaudit/auditstatemanager.h \
    service/storageaudit/auditsyncguard.h \
    common/color/namedcolor.h \
    common/csvhelper.h \
    common/csvimporter.h \
    common/eventlogger.h \
    common/filehelper.h \
    common/filenamehelper.h \
    common/logger.h \
    common/logmeta.h \
    common/movementdatahelper.h \
    common/qteventutil.h \
    common/quantityparser.h \
    common/scopedperthreadlock.h \
    common/styleprofiles/auditcolors.h \
    common/styleprofiles/cuttingcolors.h \
    common/styleprofiles/cuttingstatusutils.h \
    common/styleprofiles/relocationcolors.h \
    settings/settingsdialog.h \
    settings/settingsmeta.h \
    tests/testmanager.h \
    view/MainWindowUIBuilder.h \
    view/cellhelpers/auditstatustext.h \
    materials/view/material_cell_generator.h \
    view/columnindexes/inputtable_columns.h \
    view/columnindexes/tableresults_columns.h \
    materials/view/material_row_styler.h \
    view/common/layouts/qflowlayout.h \
    view/common/widgets/recentmaterialswidget.h \
    view/dialog/dialogmode.h \
    view/dialog/input/clonerequestdialog.h \
    view/dialog/input/matrix_cell_delegate.h \
    view/dialog/input/series_matrix_view.h \
    view/dialog/input/series_state.h \
    view/dialog/materialfinder/materialdelegate.h \
    view/dialog/materialfinder/materialfinderdialog.h \
    view/dialog/materialsearch/materialsearchdialog.h \
    view/dialog/textviewdialog.h \
    leftover/view/dialog/leftoverreviewdialog.h \
    leftover/view/dialog/scrapbybarcodedialog.h \
    view/tableutils/RowTracker.h \
    view/tableutils/auditcellformatter.h \
    view/tableutils/auditgrouplabeler.h \
    view/tableutils/auditgroupsynchronizer.h \
    view/tableutils/colorutils.h \
    view/tableutils/highlightdelegate.h \
    leftover/view/utils/leftoverstyleutils.h \
    view/tableutils/rowid.h \
    view/tableutils/storageaudittable_connector.h \
    view/tableutils/storageaudittable_rowstyler.h \
    view/tableutils/tableutils_auditcells.h \
    model/cutting/cuttingmachine.h \
    model/cutting/instruction/cutinstruction.h \
    model/cutting/optimizer/optimizermodel.h \
    model/cutting/piece/pieceinfo.h \
    model/cutting/piece/piecewithmaterial.h \
    model/cutting/plan/cutplan.h \
    model/cutting/plan/request.h \
    model/cutting/plan/source.h \
    model/cutting/plan/status.h \
    model/cutting/result/leftoversource.h \
    model/cutting/result/resultmodel.h \
    model/cutting/result/resultsource.h \
    model/cutting/segment/segmentmodel.h \
    materials/model/material_group.h \
    materials/model/material_master.h \
    materials/model/material_type.h \
    model/picking/pickingcomparisonresult.h \
    model/picking/pickingitem.h \
    model/registries/cuttingmachineregistry.h \
    model/relocation/relocationinstruction.h \
    model/relocation/relocationquantitymodel.h \
    model/relocation/relocationquantityrow.h \
    model/relocation/relocationtargetentry.h \
    model/repositories/cuttingmachinerepository.h \
    model/storageaudit/auditcontext.h \
    model/storageaudit/auditgroupinfo.h \
    model/storageaudit/auditstatus.h \
    model/storageaudit/storageauditentry.h \
    model/storageaudit/storageauditrow.h \
    service/cutting/optimizer/exporter.h \
    service/cutting/plan/autosavemanager.h \
    service/cutting/result/archivedwasteutils.h \
    service/cutting/result/leftoversourceutils.h \
    service/cutting/result/resultutils.h \
    service/cutting/segment/segmentutils.h \
    stock/service/movementlogger.h \
    settings/settingsmanager.h \
    common/startup/startupmanager.h \
    common/stringify.h \
    view/tableutils/colorlogicutils.h \
    view/tableutils/inputtable_connector.h \
    view/tableutils/inputtable_rowstyler.h \
    leftover/view/utils/leftovertable_connector.h \
    leftover/view/utils/leftovertable_rowstyler.h \
    view/tableutils/resulttable_rowstyler.h \
    stock/view/stocktable_connector.h \
    stock/view/stocktable_rowstyler.h \
    view/tablerowstyler/tablestyleutils.h \
    view/tableutils/tableutils.h \
    model/archivedwasteentry.h \
    model/crosssectionshape.h \
    model/identifiableentity.h \
    leftover/model/leftoverstockentry.h \
    model/movementdata.h \
    model/registries/cuttingplanrequestregistry.h \
    leftover/registry/leftoverstockregistry.h \
    materials/registry/material_group_registry.h \
    materials/registry/material_registry.h \
    stock/registry/stockregistry.h \
    storage/registry/storageregistry.h \
    model/repositories/cuttingrequestrepository.h \
    leftover/repository/leftoverstockrepository.h \
    materials/repository/material_group_repository.h \
    materials/repository/material_repository.h \
    stock/repository/stockrepository.h \
    storage/repository/storagerepository.h \
    storage/model/storageentry.h \
    storage/model/storagetype.h \
    presenter/CuttingPresenter.h \
    stock/service/movementlogmodel.h \
    service/relocation/relocationplanner.h \
    service/relocation/relocationservice.h \
    stock/service/stockmovementservice.h \
    service/storageaudit/auditutils.h \
    leftover/audit/leftoverauditservice.h \
    service/storageaudit/storageauditservice.h \
    view/MainWindow.h \
    view/columnindexes/tablecuttinginstruction_columns.h \
    view/eventloghelpers.h \
    view/managers/cuttinginstructiontable_manager.h \
    leftover/view/utils/leftoverreviewform_utils.h \
    view/viewmodels/audit/cellgenerator.h \
    view/viewmodels/audit/rowgenerator.h \
    view/viewmodels/cutting/rowgenerator.h \
    view/viewmodels/relocation/cellgenerator.h \
    view/viewmodels/relocation/rowgenerator.h \
    view/cellhelpers/auditcelltext.h \
    view/cellhelpers/auditcelltooltips.h \
    view/columnidexes/relocationplantable_columns.h \
    view/cutanalyticspanel.h \
    view/dialog/input/addinputdialog.h \
    leftover/view/dialog/addwastedialog.h \
    view/dialog/movement/movementdialog.h \
    view/dialog/relocation/relocationquantitydialog.h \
    stock/view/dialog/addstockdialog.h \
    stock/view/dialog/editcommentdialog.h \
    stock/view/dialog/editquantitydialog.h \
    stock/view/dialog/editstoragedialog.h \
    view/managers/inputtable_manager.h \
    leftover/view/managers/leftovertable_manager.h \
    view/managers/relocationplantable_manager.h \
    view/managers/resultstable_manager.h \
    stock/view/stocktable_manager.h \
    view/managers/storageaudittable_manager.h \
    view/tablehelpers/relocationquantityhelpers.h \
    view/tablehelpers/tablerowpopulator.h \
    view/viewmodels/request/rowgenerator.h \
    view/viewmodels/result/badgerowgenerator.h \
    view/viewmodels/result/rowgenerator.h \
    view/viewmodels/tablecellviewmodel.h \
    view/viewmodels/tablerowviewmodel.h

FORMS += \
    settings/settingsdialog.ui \
    view/MainWindow.ui \
    view/dialog/input/addinputdialog.ui \
    view/dialog/input/clonerequestdialog.ui \
    view/dialog/materialfinder/MaterialFinderDialog.ui \
    view/dialog/textviewdialog.ui \
    leftover/view/dialog/addwastedialog.ui \
    view/dialog/movement/movementdialog.ui \
    view/dialog/relocation/relocationquantitydialog.ui \
    stock/view/dialog/addstockdialog.ui \
    stock/view/dialog/editcommentdialog.ui \
    stock/view/dialog/editquantitydialog.ui \
    stock/view/dialog/editstoragedialog.ui \
    leftover/view/dialog/leftoverreviewdialog.ui \
    leftover/view/dialog/scrapbybarcodedialog.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    README.md \
    run_2.txt \
    run_3.txt \
    run_4.txt \
    run_5.txt \
    run_6.txt \
    run_7.txt \
    run_Refaktor_terv_fokuszpontok \
    testdata/bom.csv \
    testdata/csvlist.sh \
    testdata/cutting_plans/cutting_plan_1.csv \
    testdata/cutting_plans/cuttingplan_20260622-074056_hibateszt.txt \
    testdata/cutting_plans/cuttingplan_20260728-085942.txt \
    testdata/cuttingmachine_materialtypes.csv \
    testdata/cuttingmachines.csv \
    testdata/leftovers.csv \
    testdata/material_rolemap.csv \
    testdata/materialgroup_members.csv \
    testdata/materialgroups.csv \
    testdata/materials.csv \
    testdata/materials_old.csv \
    testdata/powder_consumption.csv \
    testdata/product_subtype.csv \
    testdata/ral_colors/classic.csv \
    testdata/ral_colors/design.csv \
    testdata/ral_colors/p1.csv \
    testdata/ral_colors/p2.csv \
    run.txt \
    testdata/stock.csv \
    testdata/storages.csv

RESOURCES += \
    resources/statusicons.qrc
